### ISSUE TITLE
Web Components: implement web components to be able to build the first landing page

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/odh-web-components-pagebuilder#46]
The idea is to have a list to re-create https://lp.suedtirol.info/weingenuss with web components, the store and page builder. 

We need to go through the page and extract a list of possible web components

**TODOS**
- [x] Find a developer to implement them
- [ ] Create a list of needed web components
- [ ] Integrate them into the page builder
- [ ] Build the "Weingenuss" landing page
- [ ] Test it and compare it with the original page, write a list of issues and find out about limitations

We could close all these to-dos and create proper user stories instead.

**Comment by Piiit** [comment]
@danielrampanelli @sseppi I moved this issue into this repository. 

Daniel, how far are you with this?

**Comment by ohnewein** [comment]
Just to be clear, the goal is not to create a list of web components, but to recreate an exact copy of the Weingenuss using the page builder. To do this, there will be the need to create some web components on the way.
